version: '3.4'

services:
  backend:
    image: prueba-backend
    build:
      context: .
      dockerfile: ./PruebaTecnicaChileautos/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./PruebaTecnicaChileautos/appsettings.Development.json:/app/appsettings.Development.json:ro
